version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: 1st.goapp.db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - 1st_goapp_data:/var/lib/postgresql/data

volumes:
  1st_goapp_data:
